# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f140f12bf2874199298180468729ecda4b8d8c234da2a31b5269e0f02cbacc5649e50aef7a9bf034e4c5acbddd8d6684f9db361235e2552314909a56439fbab7

test:
  secret_key_base: e220f8f706ae07c9b61e820a86b507016100c3945fab08d15863a03f5d30e80a54962acbbc411509df1a526cdcfe854428bef17b866522be7e230549a3045e62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
